version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    # for 'production' use this
    # command: bundle exec rails s -p 80 -b '0.0.0.0'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/library_mk5
    ports:
      # for 'production' use this
      # - "8001:80"
      - "3000:3000"
    depends_on:
      - db
